import { AgentCompiler } from '../../src/modules/agents/compiler/agent-compiler';

async function runCompilerSimulator() {
  console.log('[PHASE 5.5] Starting STRICT Compiler Simulator...');
  
  const compiler = new AgentCompiler();
  const prompt = "Find all mentions of Zadit and link them to muhzadit.com";

  console.log(`[1] Compiling Prompt: "${prompt}"`);
  const bytecode = compiler.compile(prompt);

  console.log(`[2] Generated Bytecode Hash: ${Buffer.from(bytecode).toString('hex')}`);
  if (bytecode.length === 0) throw new Error('Compiler generated empty bytecode');

  console.log(`[3] Validating Determinism`);
  const bytecode2 = compiler.compile(prompt);
  if (Buffer.compare(bytecode, bytecode2) !== 0) {
    throw new Error('Compiler Non-Determinism Detected!');
  }

  console.log('[SUCCESS] Compiler Replay and Integrity PASS');
}

runCompilerSimulator().catch(console.error);
